# -*- coding: utf-8 -*-
"""conjuntoscesar.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q5mWOxomZOd0E2KrMur55d7NACqk6XO3
"""

conjunto1 = {"ingles","Aleman","Italiano"}
conjunto2 = {"Chino","Japones","Aleman"}

union = conjunto1|conjunto2
print("La unión de conjunto1 y conjunto2 es:", union)

interseccion = conjunto1&conjunto2
print("La intersección de conjunto1 y conjunto2 es:", interseccion)

diferencia = conjunto1-conjunto2
print("La diferencia del conjunto 1 con el conjunto 2 es:", diferencia)

symmetric_diff = conjunto1.symmetric_difference(conjunto2)
print("La diferencia simetrica es:",symmetric_diff)

idiomas = [union]
for idioma in idiomas:
  print(f"Estoy aprendiendo {idioma}")


mi_conjunto = union(conjunto1,conjunto2)
indice = 0
#while indice < len(mi_lista):
 #   print(mi_lista[indice])
  #  indice += 1
print(mi_conjunto[1])

mi_conjunto = conjunto1.union(conjunto2)
indice = 0
#while indice < len(mi_lista):
 #   print(mi_lista[indice])
  #  indice += 1
print(mi_conjunto[1])
print("Aleman" in mi_conjunto)